###############################################
#              POWERFLY SUPPORT               #
#---------------------------------------------#
# Discord:  https://discord.gg/E2hAAa7F6q     #
###############################################

config-version: 1.7

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#       CORE SETTINGS      #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Prefix for the custom messages
prefix: "&7[&ePower&fFly&7] &r"

# Language for messages (en, es, pt, rus)
language: en

# Enable or disable update checking
check-updates: true

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#       FLY SETTINGS       #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Time in seconds before fly time is recharged after it runs out
cooldown: 100

# Fly time in seconds for new players
# You can use a number (e.g: 500) or -1 for unlimited fly time
fly-time: 100

# Fly time in seconds for each group (can be customized based on LuckPerms groups)
# You can use a number (e.g: 500) or -1 for unlimited fly time
groups-fly-time:
  default: 100
  vip: 300
  mod: 600
  admin: -1

# Prevent fall damage when fly time ends (10s)
no-fall-damage: false

# When players mine blocks while flying, they get mining fatigue effect
slow-mining:
  enabled: true
  amplifier: 2  # 0 = Mining Fatigue I, 1 = Mining Fatigue II, 2 = Mining Fatigue III, etc.

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#     COMBAT SETTINGS      #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Activate or deactivate fly when a player enters combat
disable-fly-in-combat: true

# Determine which entity prevents combat fly:
#  - "players": (PvP)
#  - "mobs": (PvE)
#  - "all": players + mobs (PvP + PvE)
combat-type: "players"

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#     DISPLAY SETTINGS     #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Show ActionBar
show-actionbar: true

# Show BossBar
show-bossbar: true

# BossBar color (options: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE)
bossbar-color: GREEN

# BossBar style (options: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20)
bossbar-style: SOLID

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#     ECONOMY SETTINGS     #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Enable or disable economy support
use-economy: false

# Symbol money
currency-symbol: $

# Price to buy fly time (1 second = 100$)
flytime-price: 100

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#    BLACKLIST SETTINGS    #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# List of worlds where players are not allowed to fly
# Supports exact names and patterns with wildcards (*)
# Examples: world_nether (exact) or dungeon* (starts with dungeon)
blacklist-worlds:
  - world_the_end
  - dungeon*

# List of regions where players not allowed to fly
blacklist-regions:
  world:
    - spawn
    - arena
  world_nether:
    - fortress
    - safe_hub
  world_the_end:
    - end_city
    - dragon_arena

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#   CLAIM FLY SETTINGS     #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Enable or disable GriefPrevention support
enable-griefprevention: true

# Enable or disable Towny support
enable-towny: true

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#     PARTICLE SETTINGS    #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Enable or disable particle effects
enable-effects: true

# List: www.minecraft.wiki/Particles_(Java_Edition)
particles:
  # Particle shown when fly is activated
  activation:
    type: CLOUD
  # Particle shown while the player is flying
  flying:
    type: END_ROD
  # Particle shown when fly is deactivated
  deactivation:
    type: SMOKE

# ━━━━━━━━━━━━━━━━━━━━━━━━ #
#      SOUND SETTINGS      #
# ━━━━━━━━━━━━━━━━━━━━━━━━ #

# Enable or disable sounds
enable-sounds: true

# List: www.minecraft.wiki/Category:Sound_effects
sounds:
  # Sound when fly is activated
  activation:
    type: BLOCK_BEACON_ACTIVATE
  # Sound when fly is deactivated
  deactivation:
    type: BLOCK_BEACON_DEACTIVATE
  # Sound when fly time ends
  time-ended:
    type: BLOCK_PORTAL_TRAVEL
